---
name: Build Hub

on:
  pull_request:
    branches:
      - main menu

jobs:
  build:
    name: Build HUb
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Buildings
        uses: Consensys/docs-gha-2023/build@main
        with:
          GITHUB_TOKEN: $$$$$${{ secrets.GITHUB_TOKEN }}
